---
- name: Provision Ansible controller with SSH key for remote
  hosts: localhost
  roles:
    - role: companieshouse.general.ssh_key
      vars:
        ssh_key_name: ansible_remote
        ssh_key_vault_path: "/applications/{{ aws_profile }}{{ vault_path }}"

- name: Run PCPlus server update
  hosts:
     - all
  become: true
  gather_facts: true
  roles:
     - pcplus_run_server_update
